### ISSUE TITLE
Error: Cannot find module 'orchestrator'

### ISSUE THREAD

**Issue by yaoshanliang** [FlorientR/laravel-gentelella#30]
iat@iat-mbp:~/workspace/code/docker/laravel-gentelella (master)$ gulp
module.js:472
    throw err;
    ^

Error: Cannot find module 'orchestrator'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/iat/workspace/code/docker/laravel-gentelella/node_modules/.3.9.1@gulp/index.js:4:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by FlorientR** [comment]
Hi ?

npm install orchestrator ?

Bye ?
